============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-7.4.3, pluggy-1.3.0
rootdir: /Users/halimlka/PycharmProjects/pytest
collected 21 items

tests/test_get_users_negative.py ...FF..F.                               [ 42%]
tests/test_get_users_positive.py ..                                      [ 52%]
tests/test_post_users_negative.py .......                                [ 85%]
tests/test_post_users_positive.py ...                                    [100%]

=================================== FAILURES ===================================
________________________ test_get_users_with_fractional ________________________

reqres_api = <framework.reqres_api.ReqresAPI object at 0x1071e1240>

    def test_get_users_with_fractional(reqres_api):
        status_code, response = reqres_api.get_users(PAGE_NEG[3])
        assert_that(status_code, equal_to(200))
>       assert_that(response.get('page'), equal_to(1))
E       AssertionError: 
E       Expected: <1>
E            but: was <6>

tests/test_get_users_negative.py:21: AssertionError
_____________________ test_get_users_with_negative_integer _____________________

reqres_api = <framework.reqres_api.ReqresAPI object at 0x1071e1240>

    def test_get_users_with_negative_integer(reqres_api):
        status_code, response = reqres_api.get_users(PAGE_NEG[4])
        assert_that(status_code, equal_to(200))
>       assert_that(response.get('page'), equal_to(1))
E       AssertionError: 
E       Expected: <1>
E            but: was <-2>

tests/test_get_users_negative.py:26: AssertionError
_____________________ test_get_users_with_per_page_max_int _____________________

reqres_api = <framework.reqres_api.ReqresAPI object at 0x1071e1240>

    def test_get_users_with_per_page_max_int(reqres_api):
        status_code, response = reqres_api.get_users_with_per_page(PAGE_NEG[7], PAGE_NEG[7])
        assert_that(status_code, equal_to(200))
>       assert_that(response.get('page'), equal_to(1))
E       AssertionError: 
E       Expected: <1>
E            but: was <9223372036854776000>

tests/test_get_users_negative.py:41: AssertionError
=========================== short test summary info ============================
FAILED tests/test_get_users_negative.py::test_get_users_with_fractional - Ass...
FAILED tests/test_get_users_negative.py::test_get_users_with_negative_integer
FAILED tests/test_get_users_negative.py::test_get_users_with_per_page_max_int
========================= 3 failed, 18 passed in 2.86s =========================
